171648108-Setup redux:(setting up redux and store)
STACK-UP-3/champs-frontend pull request #4
Opened 2020-05-14 19:45 UTC by brianineza01

#### Description
> This PR sets up Redux for being used in the APP
#### Type of change

Please select the relevant option

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Others (cosmetics, styling, improvements)
- [ ] This change requires a documentation update

#### How Has This Been Tested?

- [ ] Unit
- [ ] Integration
- [ ] End-to-end
- [ ] No testing required

#### How to Test
N/A
#### Any background context you want to add (Optional)

N/A
#### STORY ID

[Finishes #171648108]

2020-05-14 21:01 UTC, placideirandora requested changes
Open each and every file and fix those ESLint issues. ESLint is complaining a lot and once I put the file to check, If I find the issues.

2020-05-14 21:01 UTC, placideirandora commented on src/Components/App.jsx
> +          <Route exact path='/' component={Home} />
Put back the Double Quotes.  They are causing ESLint issues. These paths need to be enclosed in double-quotes as they were before.

2020-05-15 08:59 UTC, brianineza01 commented on src/Components/App.jsx
> +          <Route exact path='/' component={Home} />
Done

2020-05-15 09:07 UTC, brianineza01 commented on src/Components/App.jsx
> +          <Route exact path='/' component={Home} />
Feedback implemented

2020-05-15 10:32 UTC, placideirandora approved these changes

2020-05-15 10:35 UTC, merged